#[tool.poetry]
#name = "sqlalchemy-columns"
#version = "0.1.0"
#description = ""
#authors = []
#readme = "README.md"
#packages = [{include = "src"}]

#[tool.poetry.dependencies]
#python = ">=3.10.0"
#sqlalchemy = ">=2.0"


[build-system]
requires = ["setuptools", "wheel"]
